### PR TITLE
add clock basket piece

### PR DESCRIPTION
**Pull request by bennlich**
I have more work to do here, but this is ready for user testing + feedback on layout. In particular I haven't tested on mobile ios yet.

### CODE REVIEW

**Comment by benhylau** [comment]
When I click the text the clock moves forward and text changes, but when I click the clock the text doesn't change and only the clock moves forward. Is this intended? It took me a while to figure out the text is clickable.

**Comment by uditvira** [comment]
@s-kennedy will check out this PR if time permits

**Comment by bennlich** [comment]
> When I click the text the clock moves forward and text changes, but when I click the clock the text doesn't change and only the clock moves forward. Is this intended?

Yep, this is intended, so you can explore the shapes independently of reading the text.

> It took me a while to figure out the text is clickable.

This hasn't been a problem for people in the testing I've done so far, but I also haven't been testing it in the context of the magazine website, so it would be nice to test this version w/ a few more folks.

Is there a staging environment?

**Comment by uditvira** [comment]
> Is there a staging environment?

master is live deployed to two.compost.digital. feel free to merge to master and q/a there if you want!

**Comment by bennlich** [comment]
Sweet! Thanks. Going to bed now but I'll do this tomorrow.

**Pull request merged**
