### PR TITLE
Add blurb + image to 'Logging Off' [Ready to merge]

### PR DESCRIPTION
**Pull request by celinenguyen**
- [x] Add blurb to 'Logging Off' (I only added it to `001/index.md`—correct to assume it isn't needed for the others?)
- [x] Add image to 'Logging Off' (not ready yet, will add shortly! just wanted to push this up early)

@maisutton I went with the blurb below—your thoughts welcome but not necessary if there's a lot you're dealing with today

> **Logging Off**
> _Celine Nguyen_
>
> A gentle choose-your-own-adventure story about mushroom foraging, the weight of Indigenous history, and sustaining online community. What happens when the internet brings you closer to nature?

### CODE REVIEW

**Comment by maisutton** [comment]
hey Celine. Your piece looks so great! Love the seasonal little graphic and the layout, so happy with how it all turned out. :+1: 

Here's a version with two suggested edits for your teaser blurb:

> A gentle choose-your-own-adventure story about mushroom foraging, coming to terms with Indigenous displacement, and sustaining online community. What happens when a forum absorbs you into greater awareness and connection?

Reasons:
* Edited "Weight of Indigenous history" to be more specific regarding what part of Indigenous history the story grapples with. The heaviness of this history isn't the thousands of years of thriving before colonizers arrived, but the horrors inflicted on these tribal nations. Thought "coming to terms" was more specific about the process of these characters acknowledging this past (if an indigenous person were reading this, would they think of their own history as weight?). Also, wanted to add a gerund to mirror the other two items in this list!
* To me, the power of this piece comes from this story of someone who suddenly feels more grounded in their natural surroundings, while at the same time, more connected and fulfilled from their involvement in this online forum. Not sure if this edit hits the mark but thought it could speak to the way the protagonist has these new relationships, offline and online.

**Comment by celinenguyen** [comment]
@maisutton is it okay if we go with this? 

* I like 'coming to terms with Indigenous displacement' (clarifies positionality of non-Indigenous people thinking about this)
* I worry 'What happens when a forum absorbs you into greater awareness and connection?' is not snappy enough and would prefer to keep 'What happens when the internet brings you closer to nature?' even if it's a bit inaccurate—also perhaps 'sustaining online community' vaguely communicates the part about people/connection already?

> A gentle choose-your-own-adventure story about mushroom foraging, **coming to terms with Indigenous displacement**, and sustaining online community. What happens when **the internet brings you closer to nature?**

Working on the image now!

**Comment by celinenguyen** [comment]
Modified the blurb text to what I mentioned in my previous comment, and added the following image to `/static/images/title-images/celine-700x350.png`

celine-700x350

Some notes on image licensing:

* The background image is [this photo of a Californian forest](https://unsplash.com/photos/3z_aZ1Ajvw8) from Sarah Brown, via Unsplash. Per the [license](https://unsplash.com/license) it can be used for commercial and non-commercial purposes, and attribution isn't required.
* I also used the default title image from the repo and overlaid it on top of the forest image.
* The morel image is from a [19th cent. watercolour](https://wellcomecollection.org/works/cu4r9kht) in the Wellcome Collection. Public domain.

A screenshot of it on the main issue page! Just wanted to briefly note that at a 1078px wide viewport, the margins between the text of each piece get a bit cramped:

image

**Comment by celinenguyen** [comment]
I'm headed to bed now (1:30am BST!) but hope this is all okay for the launch tomorrow! Can check in the AM (UK time) as well if there are any outstanding issues with my piece

**Comment by maisutton** [comment]
The image is beautiful, love it so much! Also sounds re: the blurb!

M

**Pull request merged**
