### PR TITLE
Add eth address and use new buttons

### PR DESCRIPTION
**Pull request by benhylau**
I added an ETH address button and changed the styling to use the new ones. Trying to keep button styling consistent across the pages. Feel free to change if not fitting.

Screen Shot 2021-09-10 at 10 18 38 PM

Got rid of the `!` in the markdown button for simplicity.

### CODE REVIEW

**Comment by uditvira** [comment]
@s-kennedy can you take a look at this and see what you think of ben's styling?

**Comment by uditvira** [comment]
I personally feel like the "contribute eth or tokens" does not make sense next in that button with the tick. 
It could work with "contribute crypto (copy our eth address)"

**Comment by s-kennedy** [comment]
@benhylau I just removed the monospace font from the ETH button that was inconsistent with the others, and I updated the `theme-button` class to work with `a` tags so we don't have to turn our links into buttons.

**Comment by benhylau** [comment]
@s-kennedy oh thanks for all the fixes.

Just spoke with @uditvira and showed him the clicked button

Screen Shot 2021-09-15 at 4 55 07 PM

I think we can leave all the text as is. Feel free to change alignment and styling as you see fit, or leave as is.

**Review by uditvira — APPROVED** [review]

**Pull request merged**
